### ISSUE TITLE
Map error not function

### ISSUE THREAD

**Issue by MarkusSal04** [MarkusSal04/React-Your-Kindness#1]
## Unexpected Behavior

I am trying to pull data from my API, right now i keep getting an error that says 

## Expected Behavior

The component is supposed to run through the api array and render/display its data.

## Reproduce the Error

 
```md
1. Clone this repo.
2. Run `npm start`.
3. Navigate to the landing page.
4. Click on _____, which should return the API data set.
5. Scroll down to _____.
6. See the subsequent error in the console.
```

## Documentation

> Include the exact error message, and if helpful, any supplemental documentation, such as screen captures.

```md
Uncaught TypeError: quotes.map is not a function
```

## Attempted Resolution

I both google and youtubed it.

```md
1. https://forum.freecodecamp.org/t/map-is-suddenly-not-a-function/134196
2. https://www.pluralsight.com/guides/typeerror-handling-in-react.js-for-map-function

**Comment by StefonSimmons** [comment]
Needed to invoke function which made the api request

**Comment by MarkusSal04** [comment]
Did not invoke after const res = await
